### ISSUE TITLE
document that `@behaviour Arrays.Behaviour` should be called

### ISSUE THREAD

**Issue by eksperimental** [Qqwy/elixir-arrays#25]
As of now, only the empty/1 callback is required to be implemented.

**Comment by Qqwy** [comment]
This is correct. The reason for this is because `empty` is the one function which we can _not_ implement using a protocol: All protocol functions require the datastructure that we dispatch the particular implementation on to be passed as first argument. For `empty`, we are actually _creating_ this datastructure, so we don't have one to pass anywhere yet.


Maybe we can improve the documentation of this, however?

**Comment by eksperimental** [comment]
This should definitely be documented.
I have submitted a PR using this behaviour.

**Comment by Qqwy** [comment]
I am finally back after months of less time.

I have decided that the original implementation, with a separate `Array.Behaviour` (i.e. PR #31 ) is the best way to go forward for now, as the other approaches (a `@callback` in a protocol or in a nested module of a protocol) both depend on implementation details of current versions of Elixir (i.e. they do not seem 'future-proof').

**Comment by Qqwy** [comment]
In the new `master` code, this has now been thorougly documented.
Closing this issue; changes will be published in the next version, which will be `v1.0`.
