### ISSUE TITLE
How about adding a wrapper around atomics

### ISSUE THREAD

**Issue by romul** [Qqwy/elixir-arrays#92]
How about adding a wrapper around  https://www.erlang.org/doc/man/atomics.html ?
This module supports only 64 bit integers, but for this case they are much faster than `:arrays` (about 4x faster and less memory usage in benchmarks)

**Comment by Qqwy** [comment]
Hi there!

I don't think we should include such an implementation inside the Arrays library directly, since all (other) included implementations support any kind of element type.

However, it would definitely make sense as a separate sub-library, similar to e.g. [arrays_aja](https://hex.pm/packages/arrays_aja). Arrays is structured around a protocol ([`Arrays.Protocol`](https://hexdocs.pm/arrays/Arrays.Protocol.html)) so if you implement that for a struct wrapping atomics you'll be able to use all the abstractions the library provides.

**Comment by Qqwy** [comment]
I'm closing this issue now; if you want to discuss this further, feel free to open up a new issue, or to reach out on the Elixir Forum, Twitter, or elsewhere :-).
